db:
  image: postgres
  ports:
    - "5432"
  volumes:
    - .:/usr/src/my_app/db
web:
  build: .
  command: bundle exec rails s -p 3000 -b '0.0.0.0'
  ports:
    - "3000:3000"
  links:
    - db
    - redis
  volumes:
    - .:/usr/src/my_app/db
  environment:
    RAILS_ENV: production
redis:
  image: redis
