# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e8acc11a7fbfa8c67bd2550c8f8afd15946b7b6a12fbc0749c4365f3e483648b0576207ff8b9845fa365ac34c5b82ec733d499cefceb16bca0eddb5d185e7f90

test:
  secret_key_base: 94d5713fb43dbacbb3a9ac2343ff58e34ef074c7ab72335e0eadea84b9c05728fe153c33d2dd66774f5bee874739e85810c250b9023d1441f7a2e9ab08241759

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 44d5713fb43dbacbb3a9ac2343ff58e34ef074c7ab72335e0eadea84b9c05728fe153c33d2dd66774f5bee874739e85810c250b9023d1441f7a2e9ab08241759
